steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['build', '-t', 'gcr.io/group-21-project-2/testv1', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'test-image'
      - '--image=gcr.io/group-21-project-2/testv1'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'  # Adjust this based on your authentication needs
options:
  logging: CLOUD_LOGGING_ONLY
