steps:
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]
    env:
      - 'APP_SECRET_KEY=beryberysecret'
      - 'BUCKET_NAME=project-2-images'
      - 'DB_SOCKET=/cloudsql/group-21-project-2:us-central1:users'
      - 'DB_USER=root'
      - 'DB_PASSWORD=secretpass'
      - 'DB_NAME=users-db'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-east1-docker.pkg.dev/${PROJECT_ID}/testrepo/appimage:${SHORT_SHA}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push',  'us-east1-docker.pkg.dev/${PROJECT_ID}/testrepo/appimage:${SHORT_SHA}']

  - name: google/cloud-sdk
    args: [
      'gcloud', 'run', 'deploy', 'final-proj-${SHORT_SHA}', 
      '--image=us-east1-docker.pkg.dev/${PROJECT_ID}/testrepo/appimage:${SHORT_SHA}', 
      '--region', 'us-east1', '--platform', 'managed', 
      '--allow-unauthenticated',
      '--add-cloudsql-instances', 'group-21-project-2:us-central1:users'
    ]

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - us-east1-docker.pkg.dev/${PROJECT_ID}/testrepo/appimage:${SHORT_SHA}
